name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}   
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}    
jobs:
  # login to docker hub
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
  # build and push to docker hub
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: $DOCKERHUB_USERNAME/rps:$(date +%s)
      #- uses: actions/checkout@v3
      #- name: Build the Docker image
      #  run: docker build . --file Dockerfile --tag $DOCKER_USERNAME/rps:$(date +%s)
      #- name: Push the Docker image to Docker Hub
      #  run: docker push $DOCKER_USERNAME/rps:$(date +%s)
